### ISSUE TITLE
The popup windows is not working in IE

### ISSUE THREAD

**Issue by blippercop** [saschadiercks/browserStartpage#18]
The popupwindow is not working in IE. It will directly redirect to the page.

Open Page in IE
Dev tools
Click element with popup
-> Object doesn't support property or method 'forEach'

Tested on latest release.

**Comment by blippercop** [comment]
Thank you for the quick reply.
Yes, I can test anytime.

**Comment by blippercop** [comment]
That was fast!

I used the demo but unfortunately the problem persists.

When you told me that you don't have access to IE I didn't thought about giving a bit more detailed information - sry.

This may help:

![image](https://user-images.githubusercontent.com/96876285/154352647-9712a843-058c-4b5f-bc25-f5f547b4aa9d.png)
![image](https://user-images.githubusercontent.com/96876285/154352757-8b43df60-3a23-4dea-ae96-c6d0121fc7cd.png)

**Comment by saschadiercks** [comment]
Ah, too bad it didn't work. Maybe I can get an IE running in virtual box. Then I'll take a closer look next week.

**Comment by blippercop** [comment]
Sure. Appreciate the quick response!

I've never tested it but there are VM ready from MS for internet explorer: https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/

**Comment by saschadiercks** [comment]
They work pretty good. I got them running some time ago.

**Comment by saschadiercks** [comment]
I'm sorry but I need to postpone working on a solution until the end of February/beginning of march

**Comment by blippercop** [comment]
Could you already have a look into it?

**Comment by saschadiercks** [comment]
Just took a look into it. Sadly it is a bit more complicated than expected, since I'm using forEach on several places. So a greater rewrite is possibly needed. :(

**Comment by blippercop** [comment]
Ah too bad. Thanks for the update!

**Comment by saschadiercks** [comment]
Good news - today I found a workaround by fixing only one file. I tested it in IE11 under Virtualbox and it is working as intended. Modals and Flyouts are now coming up for IE11 as well.
Check it here: https://demo.saschadiercks.de/startpage/
