### ISSUE TITLE
IE / Edge

### ISSUE THREAD

**Issue by patschwork** [saschadiercks/browserStartpage#3]
Hallo Sascha, 

erstmal: Vielen Dank für die Bereitstellung. Ich nutze das Tool sehr gerne. Habe noch eine kleine Mod. angefertigt, dass Links immer im neuen Tab geöffnet werden (kann ich gerne als Patch zu Verfügung stellen bei Interesse). 

Da ich mehrere Browser verwende, ist mir aufgefallen, dass im MS IE und MS Edge alle Einträge der "Kacheln" oben links in der Ecke sind. Das Stern/Favoriten-Menü funktioniert. 

VG Patrick

**Comment by saschadiercks** [comment]
Hi Patrick,
freut mich, dass dir die Seite gefällt.

Was die Links im neuen Tab angeht, könnte ich mir vorstellen, dass als Voreinstellung zu implementieren. So dass es in der json-Datei oder der config.php bei Bedarf eingestellt werden kann. Ich hatte das bisher immer nicht umgesetzt, da ich immer mit ctrl+click einen neuen Tab öffne, aber ich denke, die Möglichkeit zu knfigurieren ist rinr gute Lösung für alle.

Was die Darstellung im IE/Edge angeht. Die beiden unterstützen kein CSS-Grid. Damüsste ich mal einen Workaround mit Flexbox/Floats entwickeln. Ich schaue mal, dass ich mir das demnächst ansehe - final im IE kann ich das aber nicht testen, da ich auf dem Mac entwickle. Ich würde dir dann eine Info mit einem Fix zukommen lassen. Eventuell könntest du das für mich testen?

Viele Grüße,
Sascha

**Comment by saschadiercks** [comment]
Hi Patrick,
check doch bitte mal den Branch aus und gib' mir Rückmeldung, wie es im IE/Edge aussieht.

Besten Dank und schönen Abend,
Sascha

**Comment by saschadiercks** [comment]
Auch das Overlay sollte nun im IE11 funktionieren

**Comment by patschwork** [comment]
Hallo Sascha, 

vielen lieben Dank für die Mühe. 
> Auch das Overlay sollte nun im IE11 funktionieren
IE11 klappt nun (wenngleich die Bilder/images im IE leider verzerrt dargestellt werden - stört mich jetzt aber nicht). 
Edge hat leider noch das Problem wie oben beschrieben.

> Ausserdem besteht nun auch die Möglichkeot ein target in der data.json anzugeben.
Mega cool - klappt wunderbar. Vielen Dank!

Viele Grüße und schönen Abend
Patrick

**Comment by saschadiercks** [comment]
Hi Patrick, ich habe es gerade noch mal im Edge testen können und bei mir tritt das Problem, dass die Kacheln obn links übereinander liegen nicht auf. Eventuell musst du den Cache einmal löschen?

Viele Grüße,
Sascha
(und sorry für die späte Rückmeldung)

**Comment by patschwork** [comment]
Hallo Sascha, 
hatte (bzw. habe grade es eben nochmal zur Sicherheit) den Cache gelöscht - leider das gleiche Ergebnis. 
Aufgefallen ist mir in der Entwicklerkonsole des Edge, dass dieser sich beschwert über einen GET zur  https://DOMAIN/browserstart/data/data.json Datei "HTTP403: VERBOTEN: Die Anforderung wurde vom Server gelesen, ihre Verarbeitung ist jedoch dort nicht zulässig.".  Die anderen Browser (IE, FF, Vivaldi) erhalten nicht diesen Fehler...

Viele Grüße und schönes WE
Patrick

PS: Kein Problem - bin ja froh, dass Du überhaupt Zeit dafür findest :-)

**Comment by saschadiercks** [comment]
Hi Patrick,
ich bin mir nicht sicher, ob der Application Cache da eventuell Fehler produziert. Du könntest mal versuchen, die Seite in einem privaten Fenster zu öffnen und schauen, ob du den Fehler dort auch bekommst. Alternativ könntest du zusätzlich mal diesen Branch ziehen und auf deinen Server werfen. (https://github.com/saschadiercks/browserStartpage/tree/feature/service-workers)
Ich entferne hier gerade den Application Cache, da der eh' deprecated ist. Da sind zwar rudimentär schon andere Inhalte drin, aber für einen kurzen Test ist es ausreichend.

Viele Grüße,
Sascha
