### ISSUE TITLE
application.manifest.php

### ISSUE THREAD

**Issue by bliwako** [saschadiercks/browserStartpage#4]
**GREAT PROJECT! Very hard to find but exactly what I was looking for!**

Ive had some caching problems. Noticed that when I open "application.manifest.php" it shows no files.

As the variables from "require_once" are not global - they dont exist in the function scope!
This affects only the "$manifestUrl".

Thank you!

**Comment by saschadiercks** [comment]
Thanks for the warm words. I‘ll look into the bug, as soon I‘m back at my PC.

**Comment by saschadiercks** [comment]
The variable is now set to global. The application-cache should work again now. :)
